### ISSUE TITLE
Possible mouse issue 

### ISSUE THREAD

**Issue by ManusMachina** [ManusMachina/Interface#3]
Moet nog geverifieerd worden

Bob:
Door de Interface te op te starten en de linker muis knop te gebruiken bugged mijn laptop.
- Als ik de Interface aan heb werkt de linker muisknop van mijn muis niet meer.

**Comment by KoningBob** [comment]
Op dinsdag 26 mei zal ik dit laten zien.

**Comment by ardentsword** [comment]
Dit is inderdaad een bekend "probleem", dit komt doordat de interface de muis probeert te "releasen" en dit gebeurt dan ook meteen als je met de echte muis de knop indrukt.

**Comment by ardentsword** [comment]
Solution: zelf bij houden of de muis is ingedrukt en alleen bij verandering een commando naar windows sturen.

**Comment by ardentsword** [comment]
Fixed in Tim-Stable https://github.com/ManusMachina/Interface/commit/2f29445a1419b39dee8648e116673133db3e8835
